version: '3.3'
services:
    mysql-docker:
        container_name: 
         mysql
        image: mysql/mysql-server:5.7
        environment:
         MYSQL_ROOT_PASSWORD: secret123456789-
         MYSQL_DATABASE: sb_db
         MYSQL_USER: superuser
         MYSQL_PASSWORD: secret123456789-
         MYSQL_ROOT_HOST: '%'
        ports:
            - 3306
        restart: always
  
    app:
        container_name: 
         demo-app
        depends_on:
         - mysql-docker
        build: 
         context: .
        restart: always
        links:
         - mysql-docker
        ports:
         - 8080:8080
